---@meta
---@class Barotrauma.GUIStyle : System.Object
---`Field Public Static`
---@field Fonts System.Collections.Immutable.ImmutableDictionary*1Barotrauma*Identifier*1Barotrauma*GUIFont|{[Barotrauma.Identifier]:Barotrauma.GUIFont}
---`Field Public Static`
---@field Sprites System.Collections.Immutable.ImmutableDictionary*1Barotrauma*Identifier*1Barotrauma*GUISprite|{[Barotrauma.Identifier]:Barotrauma.GUISprite}
---`Field Public Static`
---@field SpriteSheets System.Collections.Immutable.ImmutableDictionary*1Barotrauma*Identifier*1Barotrauma*GUISpriteSheet|{[Barotrauma.Identifier]:Barotrauma.GUISpriteSheet}
---`Field Public Static`
---@field Colors System.Collections.Immutable.ImmutableDictionary*1Barotrauma*Identifier*1Barotrauma*GUIColor|{[Barotrauma.Identifier]:Barotrauma.GUIColor}
---`Field Public Static`
---@field ComponentStyles Barotrauma.PrefabCollection*1Barotrauma*GUIComponentStyle|(fun():Barotrauma.GUIComponentStyle)
---`Field Public Static`
---@field Font Barotrauma.GUIFont
---`Field Public Static`
---@field UnscaledSmallFont Barotrauma.GUIFont
---`Field Public Static`
---@field SmallFont Barotrauma.GUIFont
---`Field Public Static`
---@field LargeFont Barotrauma.GUIFont
---`Field Public Static`
---@field SubHeadingFont Barotrauma.GUIFont
---`Field Public Static`
---@field DigitalFont Barotrauma.GUIFont
---`Field Public Static`
---@field HotkeyFont Barotrauma.GUIFont
---`Field Public Static`
---@field MonospacedFont Barotrauma.GUIFont
---`Field Public Static`
---@field CursorSprite Barotrauma.GUICursor
---`Field Public Static`
---@field SubmarineLocationIcon Barotrauma.GUISprite
---`Field Public Static`
---@field Arrow Barotrauma.GUISprite
---`Field Public Static`
---@field SpeechBubbleIcon Barotrauma.GUISprite
---`Field Public Static`
---@field BrokenIcon Barotrauma.GUISprite
---`Field Public Static`
---@field YouAreHereCircle Barotrauma.GUISprite
---`Field Public Static`
---@field Radiation Barotrauma.GUISprite
---`Field Public Static`
---@field RadiationAnimSpriteSheet Barotrauma.GUISpriteSheet
---`Field Public Static`
---@field SavingIndicator Barotrauma.GUISpriteSheet
---`Field Public Static`
---@field GenericThrobber Barotrauma.GUISpriteSheet
---`Field Public Static`
---@field UIGlow Barotrauma.GUISprite
---`Field Public Static`
---@field TalentGlow Barotrauma.GUISprite
---`Field Public Static`
---@field PingCircle Barotrauma.GUISprite
---`Field Public Static`
---@field UIGlowCircular Barotrauma.GUISprite
---`Field Public Static`
---@field UIGlowSolidCircular Barotrauma.GUISprite
---`Field Public Static`
---@field UIThermalGlow Barotrauma.GUISprite
---`Field Public Static`
---@field ButtonPulse Barotrauma.GUISprite
---`Field Public Static`
---@field WalletPortraitBG Barotrauma.GUISprite
---`Field Public Static`
---@field CrewWalletIconSmall Barotrauma.GUISprite
---`Field Public Static`
---@field EndRoundButtonPulse Barotrauma.GUISprite
---`Field Public Static`
---@field FocusIndicator Barotrauma.GUISpriteSheet
---`Field Public Static`
---@field IconOverflowIndicator Barotrauma.GUISprite
---`Field Public Static`
---@field Green Barotrauma.GUIColor
---`Field Public Static`
---@field Orange Barotrauma.GUIColor
---`Field Public Static`
---@field Red Barotrauma.GUIColor
---`Field Public Static`
---@field Blue Barotrauma.GUIColor
---`Field Public Static`
---@field Yellow Barotrauma.GUIColor
---`Field Public Static`
---@field ModdedServerColor Barotrauma.GUIColor
---`Field Public Static`
---@field ColorInventoryEmpty Barotrauma.GUIColor
---`Field Public Static`
---@field ColorInventoryHalf Barotrauma.GUIColor
---`Field Public Static`
---@field ColorInventoryFull Barotrauma.GUIColor
---`Field Public Static`
---@field ColorInventoryBackground Barotrauma.GUIColor
---`Field Public Static`
---@field ColorInventoryEmptyOverlay Barotrauma.GUIColor
---`Field Public Static`
---@field TextColorNormal Barotrauma.GUIColor
---`Field Public Static`
---@field TextColorBright Barotrauma.GUIColor
---`Field Public Static`
---@field TextColorDark Barotrauma.GUIColor
---`Field Public Static`
---@field TextColorDim Barotrauma.GUIColor
---`Field Public Static`
---@field ItemQualityColorPoor Barotrauma.GUIColor
---`Field Public Static`
---@field ItemQualityColorNormal Barotrauma.GUIColor
---`Field Public Static`
---@field ItemQualityColorGood Barotrauma.GUIColor
---`Field Public Static`
---@field ItemQualityColorExcellent Barotrauma.GUIColor
---`Field Public Static`
---@field ItemQualityColorMasterwork Barotrauma.GUIColor
---`Field Public Static`
---@field ColorReputationVeryLow Barotrauma.GUIColor
---`Field Public Static`
---@field ColorReputationLow Barotrauma.GUIColor
---`Field Public Static`
---@field ColorReputationNeutral Barotrauma.GUIColor
---`Field Public Static`
---@field ColorReputationHigh Barotrauma.GUIColor
---`Field Public Static`
---@field ColorReputationVeryHigh Barotrauma.GUIColor
---`Field Public Static`
---@field EquipmentSlotIconColor Barotrauma.GUIColor
---`Field Public Static`
---@field BuffColorLow Barotrauma.GUIColor
---`Field Public Static`
---@field BuffColorMedium Barotrauma.GUIColor
---`Field Public Static`
---@field BuffColorHigh Barotrauma.GUIColor
---`Field Public Static`
---@field DebuffColorLow Barotrauma.GUIColor
---`Field Public Static`
---@field DebuffColorMedium Barotrauma.GUIColor
---`Field Public Static`
---@field DebuffColorHigh Barotrauma.GUIColor
---`Field Public Static`
---@field HealthBarColorLow Barotrauma.GUIColor
---`Field Public Static`
---@field HealthBarColorMedium Barotrauma.GUIColor
---`Field Public Static`
---@field HealthBarColorHigh Barotrauma.GUIColor
---`Getter Public Static`
---@field ItemFrameMargin Microsoft.Xna.Framework.Point
---`Getter Public Static`
---@field ItemFrameOffset Microsoft.Xna.Framework.Point
_G['GUI']['GUIStyle'] = {}

---`Method Public Static`
---@overload fun(styleName:System.String|string):Barotrauma.GUIComponentStyle
---@param identifier Barotrauma.Identifier
---@return Barotrauma.GUIComponentStyle
_G['GUI']['GUIStyle'].GetComponentStyle = function(identifier) end

---`Method Public Static`
---@overload fun(targetComponent:Barotrauma.GUIComponent, styleName?:System.String|string, parent?:Barotrauma.GUIComponent)
---@param targetComponent Barotrauma.GUIComponent
---@param styleName Barotrauma.Identifier
---@param parent? Barotrauma.GUIComponent
_G['GUI']['GUIStyle'].Apply = function(targetComponent, styleName, parent) end

---`Method Public Static`
---@param quality System.Int32|integer
---@return Barotrauma.GUIColor
_G['GUI']['GUIStyle'].GetQualityColor = function(quality) end

---`Method Public Static`
_G['GUI']['GUIStyle'].RecalculateFonts = function() end

---`Method Public Static`
_G['GUI']['GUIStyle'].RecalculateSizeRestrictions = function() end

---`Constructor Private Static`
---@return Barotrauma.GUIStyle
_G['GUI']['GUIStyle'] = function() end

---`Constructor Private Static`
---@return Barotrauma.GUIStyle
_G['GUI']['GUIStyle'].__new = function() end

