---@meta
---@class Microsoft.Xna.Framework.Color : System.ValueType
---@operator mul(System.Single|number):Microsoft.Xna.Framework.Color
---`Field Private Instance`
---@field _packedValue System.UInt32|integer
---`Getter Public Instance`
---<br/>`Setter Public Instance`
---@field B System.Byte|integer
---`Getter Public Instance`
---<br/>`Setter Public Instance`
---@field G System.Byte|integer
---`Getter Public Instance`
---<br/>`Setter Public Instance`
---@field R System.Byte|integer
---`Getter Public Instance`
---<br/>`Setter Public Instance`
---@field A System.Byte|integer
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field TransparentBlack Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Transparent Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field AliceBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field AntiqueWhite Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Aqua Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Aquamarine Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Azure Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Beige Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Bisque Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Black Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field BlanchedAlmond Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Blue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field BlueViolet Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Brown Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field BurlyWood Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field CadetBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Chartreuse Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Chocolate Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Coral Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field CornflowerBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Cornsilk Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Crimson Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Cyan Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkCyan Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkGoldenrod Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkKhaki Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkMagenta Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkOliveGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkOrange Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkOrchid Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkRed Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkSalmon Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkSeaGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkSlateBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkSlateGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkTurquoise Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DarkViolet Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DeepPink Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DeepSkyBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DimGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field DodgerBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Firebrick Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field FloralWhite Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field ForestGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Fuchsia Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Gainsboro Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field GhostWhite Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Gold Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Goldenrod Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Gray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Green Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field GreenYellow Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Honeydew Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field HotPink Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field IndianRed Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Indigo Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Ivory Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Khaki Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Lavender Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LavenderBlush Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LawnGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LemonChiffon Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightCoral Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightCyan Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightGoldenrodYellow Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightPink Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightSalmon Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightSeaGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightSkyBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightSlateGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightSteelBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LightYellow Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Lime Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field LimeGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Linen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Magenta Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Maroon Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumAquamarine Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumOrchid Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumPurple Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumSeaGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumSlateBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumSpringGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumTurquoise Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MediumVioletRed Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MidnightBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MintCream Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MistyRose Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Moccasin Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field MonoGameOrange Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field NavajoWhite Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Navy Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field OldLace Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Olive Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field OliveDrab Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Orange Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field OrangeRed Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Orchid Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PaleGoldenrod Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PaleGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PaleTurquoise Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PaleVioletRed Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PapayaWhip Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PeachPuff Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Peru Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Pink Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Plum Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field PowderBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Purple Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Red Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field RosyBrown Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field RoyalBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SaddleBrown Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Salmon Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SandyBrown Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SeaGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SeaShell Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Sienna Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Silver Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SkyBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SlateBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SlateGray Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Snow Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SpringGreen Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field SteelBlue Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Tan Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Teal Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Thistle Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Tomato Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Turquoise Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Violet Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Wheat Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field White Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field WhiteSmoke Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field Yellow Microsoft.Xna.Framework.Color
---`Getter Public Static`
---<br/>`Setter Private Static`
---@field YellowGreen Microsoft.Xna.Framework.Color
---`Getter Public Instance`
---<br/>`Setter Public Instance`
---@field PackedValue System.UInt32|integer
---`Getter NonPublic Instance`
---@field DebugDisplayString System.String|string
_G['Color'] = {}

---`Method Public Static`
---@param value1 Microsoft.Xna.Framework.Color
---@param value2 Microsoft.Xna.Framework.Color
---@param amount System.Single|number
---@return Microsoft.Xna.Framework.Color
_G['Color'].Lerp = function(value1, value2, amount) end

---`Method Public Instance`
---@return Microsoft.Xna.Framework.Vector3
_G['Color'].ToVector3 = function() end

---`Method Public Instance`
---@return Microsoft.Xna.Framework.Vector4
_G['Color'].ToVector4 = function() end

---`Method Public Instance Virtual`
---@return System.String|string
_G['Color'].ToString = function() end

---`Method Public Instance Virtual`
---@overload fun(other:Microsoft.Xna.Framework.Color):System.Boolean|boolean
---@param obj System.Object
---@return System.Boolean|boolean
_G['Color'].Equals = function(obj) end

---`Method Public Instance Virtual`
---@return System.Int32|integer
_G['Color'].GetHashCode = function() end

---`Constructor Private Static`
---@overload fun():Microsoft.Xna.Framework.Color
---@overload fun(packedValue:System.UInt32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector4):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector3):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@param r System.Byte|integer
---@param g System.Byte|integer
---@param b System.Byte|integer
---@param alpha System.Byte|integer
---@return Microsoft.Xna.Framework.Color
_G['Color'] = function(r, g, b, alpha) end

---`Constructor Private Static`
---@overload fun():Microsoft.Xna.Framework.Color
---@overload fun(packedValue:System.UInt32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector4):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector3):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@param r System.Byte|integer
---@param g System.Byte|integer
---@param b System.Byte|integer
---@param alpha System.Byte|integer
---@return Microsoft.Xna.Framework.Color
_G['Color'].__new = function(r, g, b, alpha) end

---`Constructor Public Instance`
---@overload fun():Microsoft.Xna.Framework.Color
---@overload fun(packedValue:System.UInt32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector4):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector3):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@param r System.Byte|integer
---@param g System.Byte|integer
---@param b System.Byte|integer
---@param alpha System.Byte|integer
---@return Microsoft.Xna.Framework.Color
_G['Color'] = function(r, g, b, alpha) end

---`Constructor Public Instance`
---@overload fun():Microsoft.Xna.Framework.Color
---@overload fun(packedValue:System.UInt32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector4):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Vector3):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(color:Microsoft.Xna.Framework.Color, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Single|number, g:System.Single|number, b:System.Single|number, alpha:System.Single|number):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer):Microsoft.Xna.Framework.Color
---@overload fun(r:System.Int32|integer, g:System.Int32|integer, b:System.Int32|integer, alpha:System.Int32|integer):Microsoft.Xna.Framework.Color
---@param r System.Byte|integer
---@param g System.Byte|integer
---@param b System.Byte|integer
---@param alpha System.Byte|integer
---@return Microsoft.Xna.Framework.Color
_G['Color'].__new = function(r, g, b, alpha) end

