---@meta
---@class Barotrauma.GUISoundType : System.Enum
---`Field Public Static`
---@field UIMessage Barotrauma.GUISoundType
---`Field Public Static`
---@field ChatMessage Barotrauma.GUISoundType
---`Field Public Static`
---@field RadioMessage Barotrauma.GUISoundType
---`Field Public Static`
---@field DeadMessage Barotrauma.GUISoundType
---`Field Public Static`
---@field Select Barotrauma.GUISoundType
---`Field Public Static`
---@field PickItem Barotrauma.GUISoundType
---`Field Public Static`
---@field PickItemFail Barotrauma.GUISoundType
---`Field Public Static`
---@field DropItem Barotrauma.GUISoundType
---`Field Public Static`
---@field PopupMenu Barotrauma.GUISoundType
---`Field Public Static`
---@field Decrease Barotrauma.GUISoundType
---`Field Public Static`
---@field Increase Barotrauma.GUISoundType
---`Field Public Static`
---@field UISwitch Barotrauma.GUISoundType
---`Field Public Static`
---@field TickBox Barotrauma.GUISoundType
---`Field Public Static`
---@field ConfirmTransaction Barotrauma.GUISoundType
---`Field Public Static`
---@field Cart Barotrauma.GUISoundType
_G['GUISoundType'] = {}

