---@meta
---@class Barotrauma.Pivot : System.Enum
---`Field Public Static`
---@field TopLeft Barotrauma.Pivot
---`Field Public Static`
---@field TopCenter Barotrauma.Pivot
---`Field Public Static`
---@field TopRight Barotrauma.Pivot
---`Field Public Static`
---@field CenterLeft Barotrauma.Pivot
---`Field Public Static`
---@field Center Barotrauma.Pivot
---`Field Public Static`
---@field CenterRight Barotrauma.Pivot
---`Field Public Static`
---@field BottomLeft Barotrauma.Pivot
---`Field Public Static`
---@field BottomCenter Barotrauma.Pivot
---`Field Public Static`
---@field BottomRight Barotrauma.Pivot
_G['GUI']['Pivot'] = {}

