---@meta
---@class Barotrauma.InvSlotType : System.Enum
---`Field Public Static`
---@field None Barotrauma.InvSlotType
---`Field Public Static`
---@field Any Barotrauma.InvSlotType
---`Field Public Static`
---@field RightHand Barotrauma.InvSlotType
---`Field Public Static`
---@field LeftHand Barotrauma.InvSlotType
---`Field Public Static`
---@field Head Barotrauma.InvSlotType
---`Field Public Static`
---@field InnerClothes Barotrauma.InvSlotType
---`Field Public Static`
---@field OuterClothes Barotrauma.InvSlotType
---`Field Public Static`
---@field Headset Barotrauma.InvSlotType
---`Field Public Static`
---@field Card Barotrauma.InvSlotType
---`Field Public Static`
---@field Bag Barotrauma.InvSlotType
---`Field Public Static`
---@field HealthInterface Barotrauma.InvSlotType
_G['InvSlotType'] = {}

