---@meta
---@class Barotrauma.StatusEffect.TargetType : System.Enum
---`Field Public Static`
---@field This Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field Parent Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field Character Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field Contained Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field NearbyCharacters Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field NearbyItems Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field UseTarget Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field Hull Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field Limb Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field AllLimbs Barotrauma.StatusEffect.TargetType
---`Field Public Static`
---@field LastLimb Barotrauma.StatusEffect.TargetType
_G['StatusEffect']['TargetType'] = {}

